<section class="section-intro">
    <div class="container">
        <h2>Váš košík</h2>
        <div class="cart">
            <div class="cart__items">
                <div class="cart__item">
                    <img class="cart__item--image" src="assets/images/product.webp" alt="#">
                    <div class="cart__item--name">Název produktu</div>
                    <div class="cart__item--counter">1x</div>
                    <div class="cart__item--price">250 Kč</div>
                    <div class="cart__item--delete">&#10005;</div>
                </div>
                <div class="cart__item">
                    <img class="cart__item--image" src="assets/images/product.webp" alt="#">
                    <div class="cart__item--name">Název produktu</div>
                    <div class="cart__item--counter">1x</div>
                    <div class="cart__item--price">250 Kč</div>
                    <div class="cart__item--delete">&#10005;</div>
                </div>
            </div>
            <div class="summary">
                <h2 class="summary__title">Shrnutí</h2>
                <div class="summary__count">
                    <div class="summary__count--total">Celkem</div>
                    <div class="summary__count--price">250 Kč</div>

                </div>


                <button class="button-next">Další krok</button>
            </div>

        </div>


    </div>
</section>