<section class="section-intro">
    <div class="container">
        <div class="category-select">
            <h2 class="category-title">Název kategorie</h2>
            <select class="select">
                <option selected disabled>Vyberte kategorii</option>
                <option value="#"></option>
                <option value="#"></option>
            </select>

        </div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin lacus ex, pretium eget congue nec, iaculis ullamcorper ex. Praesent convallis, enim ac semper aliquam, magna nisi consectetur nibh, vel efficitur sapien tortor non turpis. Duis vehicula mauris et risus pulvinar, at placerat enim tincidunt. Donec vehicula libero id mi molestie lobortis. In eget pulvinar eros, sit amet dignissim tortor.</p>

        <div class="grid">
            <div class="grid-item">
                <div class="grid-item__image"><img src="assets/images/product.webp"></div>
                <div class="grid-item__title"><a href="#">Kávová zrna</a></div>
                <div class="grid-item__price"><a href="#">250 Kč</a></div>
                <button class="button-cart">Přidat do košíku</button>
            </div>
            <div class="grid-item">
                <div class="grid-item__image"><img src="assets/images/product.webp"></div>
                <div class="grid-item__title"><a href="#">Kávová zrna</a></div>
                <div class="grid-item__price"><a href="#">250 Kč</a></div>
                <button class="button-cart">Přidat do košíku</button>
            </div>
            <div class="grid-item">
                <div class="grid-item__image"><img src="assets/images/product.webp"></div>
                <div class="grid-item__title"><a href="#">Kávová zrna</a></div>
                <div class="grid-item__price"><a href="#">250 Kč</a></div>
                <button class="button-cart">Přidat do košíku</button>
            </div>
        </div>
    </div>
</section>