<section class="section-intro">
    <div class="container">
        <div class="category-select">
            <h2 class="category-title">Název kategorie</h2>
            <select class="select">
                <option selected disabled>Vyberte kategorii</option>
                <option value="#"></option>
                <option value="#"></option>
            </select>

        </div>

        <div class="grid">
            <div class="grid-item">
                <div class="grid-item__image"><img src="assets/images/product.webp"></div>
                <div class="grid-item__title"><a href="#">Kávová zrna</a></div>
                <div class="grid-item__price"><a href="#">250 Kč</a></div>
                <button class="button-cart">Přidat do košíku</button>
            </div>
            <div class="grid-item">
                <div class="grid-item__image"><img src="assets/images/product.webp"></div>
                <div class="grid-item__title"><a href="#">Kávová zrna</a></div>
                <div class="grid-item__price"><a href="#">250 Kč</a></div>
                <button class="button-cart">Přidat do košíku</button>
            </div>
            <div class="grid-item">
                <div class="grid-item__image"><img src="assets/images/product.webp"></div>
                <div class="grid-item__title"><a href="#">Kávová zrna</a></div>
                <div class="grid-item__price"><a href="#">250 Kč</a></div>
                <button class="button-cart">Přidat do košíku</button>
            </div>
        </div>
    </div>
</section>