<section class="section-intro">
    <div class="container">
        <h2>Detaily objednávky</h2>
        <div class="checkout">
            <div class="checkout__items">
                <div class="checkout__item">
                    <h3>Fakturační údaje</h3>
                    <form class="form" action="#">
                        <fieldset>
                            <label for="fname">Jméno:</label>
                            <input type="text" id="fname" name="fname">
                            <label for="lname">Příjmení:</label>
                            <input type="text" id="lname" name="lname">
                            <label for="email">E-mail:</label>
                            <input type="email" id="email" name="email">
                            <label for="street">Ulice:</label>
                            <input type="text" id="street" name="street">
                            <label for="town">Město</label>
                            <input type="text" id="town" name="town">
                            <label for="pcode">PSČ:</label>
                            <input type="number" id="pcode" name="pcode">
                        </fieldset>
                    </form>
                </div>
                <div class="checkout__item">
                    <h3>Doprava</h3>
                    <form class="form" action="#">
                        <fieldset>
                            <span>Vyberte způsob dopravy:</span>
                            <div>
                                <input type="radio" id="post" name="transport" value="post">
                                <label for="post">Česká pošta</label>
                            </div>
                            <div>
                                <input type="radio" id="ppl" name="transport" value="ppl">
                                <label for="ppl">PPL</label>
                            </div>
                            <div>
                                <input type="radio" id="dpd" name="transport" value="dpd">
                                <label for="dpd">DPD</label>
                            </div>
                        </fieldset>
                    </form>
                </div>
                <div class="checkout__item">
                    <h3>Platba</h3>
                    <form class="form" action="#">
                        <fieldset>
                            <span>Vyberte způsob platby:</span>
                            <div>
                                <input type="radio" id="cash" name="payment" value="cash">
                                <label for="cash">Dobírka</label>
                            </div>
                            <div>
                                <input type="radio" id="transfer" name="payment" value="transfer">
                                <label for="transfer">Bankovní převod</label>
                            </div>
                            <div>
                                <input type="radio" id="apay" name="payment" value="apay">
                                <label for="apay">Apple pay</label>
                            </div>

                        </fieldset>
                    </form>

                    <form class="form" action="#">
                        <fieldset>
                        </fieldset>
                    </form>

                </div>
            </div>
            <div class="summary">
                <h2 class="summary__title">Shrnutí</h2>
                <div class="summary__count">
                    <div class="summary__count--total">Doprava</div>
                    <div class="summary__count--price">50 Kč</div>
                </div>
                <div class="summary__count">
                    <div class="summary__count--total">Celkem</div>
                    <div class="summary__count--price">250 Kč</div>

                </div>

                <button type="submit" class="button-next">Odeslat objednávku</button>
            </div>
        </div>
    </div>
</section>