<section class="section-intro">
    <div class="container">
        <h2>Váš účet</h2>
        <div class="client">
            <div class="client__items">

                <div class="client__item">
                    <h3>Vaše osobní údaje</h3>
                    <form class="form" action="ucet" method="post">
                        <fieldset>
                            <label for="fname">Jméno:</label>
                            <input type="text" id="fname" name="fname" value="<?= $user["fname"] ?>">
                            <label for="lname">Příjmení:</label>
                            <input type="text" id="lname" name="lname" value="<?= $user["lname"] ?>">
                            <label for=" email">E-mail:</label>
                            <input type="email" id="email" name="email" value="<?= $user["email"] ?>">


                            <label for=" street">Ulice:</label>
                            <input type="text" id="street" name="street" value="<?= $user["street"] ?>">
                            <label for=" town">Město</label>
                            <input type="text" id="town" name="town" value="<?= $user["town"] ?>">
                            <label for=" pcode">PSČ:</label>
                            <input type="number" id="pcode" name="pcode" value="<?= $user["pcode"] ?>">

                            <button type=" submit" class="button-next">Změnit osobní údaje</button>

                        </fieldset>
                    </form>
                </div>

                <div class="client__item">
                    <h3>Vaše objednávky</h3>
                    <div class="orders">
                        <div class="order">
                            <div class="order__date">1. 1. 2024</div>
                            <div class="order__count">4 ks</div>
                            <div class="order__total">500 Kč</div>
                        </div>
                        <div class="order">
                            <div class="order__date">2. 1. 2024</div>
                            <div class="order__count">2 ks</div>
                            <div class="order__total">500 Kč</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>