<section class="section-intro">
    <!-- <div class="section-intro-bg"></div> -->
    <div class="container">
        <h2>Nadpis</h2>
        <div class="grid">
            <div class="grid-item">
                <div class="grid-item__image"><img src="assets/images/product.webp"></div>
                <div class="grid-item__title"><a href="#">Kávová zrna</a></div>
                <div class="grid-item__price"><a href="#">250 Kč</a></div>
                <button class="button-cart">Přidat do košíku</button>
            </div>
            <div class="grid-item">
                <div class="grid-item__image"><img src="assets/images/product.webp"></div>
                <div class="grid-item__title"><a href="#">Kávová zrna</a></div>
                <div class="grid-item__price"><a href="#">250 Kč</a></div>
                <button class="button-cart">Přidat do košíku</button>
            </div>
            <div class="grid-item">
                <div class="grid-item__image"><img src="assets/images/product.webp"></div>
                <div class="grid-item__title"><a href="#">Kávová zrna</a></div>
                <div class="grid-item__price"><a href="#">250 Kč</a></div>
                <button class="button-cart">Přidat do košíku</button>
            </div>
        </div>
    </div>
</section>