<section class="section-intro">
    <!-- <div class="section-intro-bg"></div> -->
    <div class="container grid">
        <div class="grid-item">
            <div class="grid-item__image"><img src="assets/images/product.webp"></div>
            <div class="grid-item__title"><a href="#">Kávová zrna</a></div>
            <div class="grid-item__price"><a href="#">250 Kč</a></div>
            <button>Přidat do košíku</button>
        </div>
        <div class="grid-item">
            <div class="grid-item__image"><img src="assets/images/product.webp"></div>
            <div class="grid-item__title"><a href="#">Kávová zrna</a></div>
            <div class="grid-item__price"><a href="#">250 Kč</a></div>
            <button>Přidat do košíku</button>
        </div>
        <div class="grid-item">
            <div class="grid-item__image"><img src="assets/images/product.webp"></div>
            <div class="grid-item__title"><a href="#">Kávová zrna</a></div>
            <div class="grid-item__price"><a href="#">250 Kč</a></div>
            <button>Přidat do košíku</button>
        </div>
    </div>
</section>