<section class="section-intro">
    <div class="container">
        <h2>Název kategorie</h2>
        <div class="grid">
            <?php foreach ($products as $product) : ?>
                <div class="grid-item">
                    <div class="grid-item__image"><img src="assets/images/product.webp"></div>
                    <div class="grid-item__title"><a href="#"><?= $product["title"] ?></a></div>
                    <div class="grid-item__price"><a href="#"><?= $product["price"] ?> Kč</a></div>
                    <button class="button-cart">Přidat do košíku</button>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</section>