<section class="section-intro">
    <div class="container">
        <div class="product">
            <h2>Detail produktu</h2>
            <div class="product_image">
                <img src="assets/images/product.webp">
            </div>
            <div class="product-details">
                <div class="product-details__title">Kávová zrna</div>
                <div class="product-details__price">250 Kč</div>
                <button class="button-cart">Přidat do košíku</button>
                <div class="product-details__shortdesc">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas aliquet orci dignissim, gravida ante at, accumsan nisi. Maecenas ac mollis nisi, a rhoncus lacus.
                    </p>

                </div>

                <div class="product-details__longdesc">
                    <p>

                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas aliquet orci dignissim, gravida ante at, accumsan nisi. Maecenas ac mollis nisi, a rhoncus lacus. Donec congue rhoncus malesuada. Proin finibus nibh fermentum nulla rhoncus, et hendrerit ex fringilla. Proin ac semper lectus. Donec id convallis nunc, nec aliquet sapien. Nunc vitae massa enim. Fusce vehicula suscipit mi quis vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.
                    </p>

                </div>

            </div>

        </div>
    </div>
</section>