<section class="section-intro">
    <div class="container">
        <h2>Přihlásit se</h2>
        <div class="sign">
            <form class="form" action="#">
                <fieldset>
                    <label for="email">E-mail:</label>
                    <input type="email" id="email" name="email">

                    <label for="password">Heslo:</label>
                    <input type="password" id="password" name="password">

                    <button type="submit" class="button-next">Přihlásit se</button>


                    <span>Nemáte účet? <a href="#">Registujte se</a></span>
                </fieldset>
            </form>

        </div>



    </div>
</section>