<section class="section-intro">
    <div class="container">
        <h2>Registrace</h2>
        <div class="sign">
            <form class="form" action="#">
                <fieldset>
                    <label for="fname">Jméno:</label>
                    <input type="text" id="fname" name="fname">
                    <label for="lname">Příjmení:</label>
                    <input type="text" id="lname" name="lname">

                    <label for="street">Ulice:</label>
                    <input type="text" id="street" name="street">
                    <label for="town">Město</label>
                    <input type="text" id="town" name="town">
                    <label for="pcode">PSČ:</label>
                    <input type="number" id="pcode" name="pcode">


                    <label for="email">E-mail:</label>
                    <input type="email" id="email" name="email">

                    <label for="password">Heslo:</label>
                    <input type="password" id="password" name="password">
                    <span>Již máte účet? <a href="#">Přihlaste se</a></span>
                </fieldset>
            </form>

        </div>



    </div>
</section>