<!-- <form class="form" action="product" method="post">
    <fieldset>
        <label for="url">url:</label>
        <input type="text" id="url" name="url" value="<?= $category["url"] ?>">
        <label for="title">Název:</label>
        <input type="text" id="title" name="title" value="<?= $category["title"] ?>">
        <label for="descript">Popis:</label>
        <input type="text" id="descript" name="descript" value="<?= $category["descript"] ?>">

        <button type="save" class="button-next">Uložit</button>
    </fieldset>
</form> -->