<div class="content-top">
    <h3>Správa zákazníků</h3>
    <a href="/admin/clients/edit"><button type="button" class="button-next">Nový zákazník</button></a>
</div>

<div class="tg-wrap">
    <table class="tg">
        <thead>
            <tr>
                <th class="tg-0pky">Jméno</th>
                <th class="tg-0pky">Příjmení</th>
                <th class="tg-0pky">E-mail</th>
                <th class="tg-0pky">Ulice</th>
                <th class="tg-0pky">Město</th>
                <th class="tg-0pky">PSČ</th>
                <th class="tg-0pky">Upravit</th>
                <th class="tg-0pky">Odstranit</th>

            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $user) : ?>
                <tr>
                    <td class="tg-pcvp"><?= $user["fname"] ?></td>
                    <td class="tg-pcvp"><?= $user["lname"] ?></td>
                    <td class="tg-pcvp"><?= $user["email"] ?></td>
                    <td class="tg-pcvp"><?= $user["street"] ?></td>
                    <td class="tg-pcvp"><?= $user["town"] ?></td>
                    <td class="tg-pcvp"><?= $user["pcode"] ?></td>
                    <td class="tg-pcvp"><a href="/admin/clients/edit?id=<?= $product["id"] ?>"><i class="fa-solid fa-pencil edit-pencil"></i></a></td>
                    <td class="tg-pcvp"><a href="#"><i class="fa-solid fa-trash delete-icon"></a></i></td>

                </tr>
            <?php endforeach ?>

        </tbody>
    </table>
</div>