<form class="form" action="/admin/categories/edit?id=<?= $_GET["id"] ?>" method="post">
    <fieldset>
        <label for="url">url:</label>
        <input type="text" id="url" name="url" value="<?= $category["url"] ?>">
        <label for="title">Název:</label>
        <input type="text" id="title" name="title" value="<?= $category["title"] ?>">
        <label for="descript">Popis:</label>
        <textarea type="text" id="descript" name="descript" rows="6"><?= $category["descript"] ?></textarea>

        <button type="submit" class="button-next">Uložit</button>
    </fieldset>
</form>