<form class="form" action="/admin/products/edit?id=<?= $_GET["id"] ?>" method="post">
    <fieldset>
        <label for="title">Název:</label>
        <input type="text" id="title" name="title" value="<?= $product["title"] ?>">
        <label for="price">Cena:</label>
        <input type="text" id="price" name="price" value="<?= $product["price"] ?>">
        <label for="shortdesc">Krátký popis:</label>
        <textarea type="text" id="shortdesc" name="shortdesc" rows="4"><?= $product["shortdesc"] ?></textarea>
        <label for="longdesc">Dlouhý popis:</label>
        <textarea type="text" id="longdesc" name="longdesc" rows="8"><?= $product["longdesc"] ?></textarea>
        <label for="image">Obrázek:</label>
        <input type="file" id="image" name="image" accept="image/*" value="<?= $product["image"] ?>">
        <label for="image">Kategorie:</label>
        <select id="categories_id" name="categories_id">
            <?php foreach ($categories as $category) : ?>
                <option><?= $category['id'] ?></option>
            <?php endforeach ?>
        </select>

        <button type="submit" class="button-next">Uložit</button>
    </fieldset>
</form>