<form class="form" action="/admin/categories/edit" method="post">
    <fieldset>
        <label for="url">url:</label>
        <input type="text" id="url" name="url">
        <label for="title">Název:</label>
        <input type="text" id="title" name="title">
        <label for="descript">Popis:</label>
        <textarea type="text" id="descript" name="descript" rows="6"></textarea>

        <button type="submit" class="button-next">Uložit</button>
    </fieldset>
</form>