<form class="form" action="/admin/client/edit" method="post">
    <fieldset>
        <label for="fname">Jméno:</label>
        <input type="text" id="fname" name="fname">
        <label for="lname">Příjmení:</label>
        <input type="text" id="lname" name="lname">
        <label for="email">E-mail:</label>
        <input type="text" id="email" name="email">
        <label for="street">Ulice:</label>
        <input type="text" id="street" name="street">
        <label for="town">Město:</label>
        <input type="text" id="town" name="town">
        <label for="pcode">PSČ:</label>
        <input type="text" id="pcode" name="pcode">

        <button type="submit" class="button-next">Uložit</button>
    </fieldset>
</form>