<div class="tg-wrap">
    <table class="tg">
        <thead>
            <tr>
                <th class="tg-0pky">Název</th>
                <th class="tg-0pky">Cena</th>
                <th class="tg-0pky">Upravit</th>

            </tr>
        </thead>
        <tbody>
            <?php foreach ($payments as $payment) : ?>
                <tr>
                    <td class="tg-pcvp"><?= $payment["title"] ?></td>
                    <td class="tg-pcvp"><?= $payment["price"] ?></td>
                    <td class="tg-pcvp"><a href="/admin/payments/edit?id=<?= $payment["id"] ?>"><i class="fa-solid fa-pencil edit-pencil"></i></a></td>
                </tr>
            <?php endforeach ?>

        </tbody>
    </table>
</div>