<div class="tg-wrap">
    <table class="tg">
        <thead>
            <tr>
                <th class="tg-0pky">Název</th>
                <th class="tg-0pky">Cena</th>
                <th class="tg-0pky">Krátký popis</th>
                <th class="tg-0pky">Dlouhý popis</th>
                <th class="tg-0pky">Obrázek</th>
                <th class="tg-0pky">Kategorie</th>
                <th class="tg-0pky">Upravit</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($products as $product) : ?>
                <tr>
                    <td class="tg-pcvp"><?= $product["title"] ?></td>
                    <td class="tg-pcvp"><?= $product["price"] ?></td>
                    <td class="tg-pcvp"><?= $product["shortdesc"] ?></td>
                    <td class="tg-pcvp"><?= $product["longdesc"] ?></td>
                    <td class="tg-pcvp"><?= $product["image"] ?></td>
                    <td class="tg-pcvp"><?= $product["categories_id"] ?></td>
                    <td class="tg-pcvp"><a href="/admin/products/edit?id=<?= $product["id"] ?>"><i class="fa-solid fa-pencil edit-pencil"></i></a></td>
                </tr>
            <?php endforeach ?>

        </tbody>
    </table>
</div>