<div class="content-top">
    <h3>Správa doprav</h3>
    <a href="/admin/transports/edit"><button type="button" class="button-next">Nový typ dopravy</button></a>
</div>
<div class="tg-wrap">
    <table class="tg">
        <thead>
            <tr>
                <th class="tg-0pky">Název</th>
                <th class="tg-0pky">Cena</th>
                <th class="tg-0pky">Upravit</th>
                <th class="tg-0pky">Odstranit</th>


            </tr>
        </thead>
        <tbody>
            <?php foreach ($transports as $transport) : ?>
                <tr>
                    <td class="tg-pcvp"><?= $transport["title"] ?></td>
                    <td class="tg-pcvp"><?= $transport["price"] ?></td>
                    <td class="tg-pcvp"><a href="/admin/transports/edit?id=<?= $transport["id"] ?>"><i class="fa-solid fa-pencil edit-pencil"></i></a></td>
                    <td class="tg-pcvp"><a href="#"><i class="fa-solid fa-trash delete-icon"></a></i></td>

                </tr>
            <?php endforeach ?>

        </tbody>
    </table>
</div>